global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost']
    metrics_path: /prometheus/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost']
    metrics_path: /node-exporter/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
