# Generated by Django 4.2.11 on 2025-03-02 23:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('player1_id', models.CharField(blank=True, max_length=100, null=True)),
                ('player2_id', models.CharField(blank=True, max_length=100, null=True)),
                ('winner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_x', models.FloatField(default=50.0)),
                ('ball_y', models.FloatField(default=50.0)),
                ('ball_dx', models.FloatField(default=0.5)),
                ('ball_dy', models.FloatField(default=0.5)),
                ('player1_position', models.FloatField(default=50.0)),
                ('player2_position', models.FloatField(default=50.0)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='online_game.game')),
            ],
        ),
    ]
