# Generated by Django 5.1.7 on 2025-03-21 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='online_game.game')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
