filebeat.inputs:
- type: docker
  containers:
    path: "/var/lib/docker/containers"
    ids: ["*"]
  json.message_key: "log"
  json.keys_under_root: true
  json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
