name: 42_transcendence

services:
    nginx:
        image: nginx:reverse-proxy
        container_name: nginx
        build:
            context: ./infrastructure/nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - frontend-files:/www:ro
            - shared-static_files:/app/media:rw
        networks:
            42network:
                aliases:
                    - nginx
        depends_on:
            redis:
                condition: service_healthy
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        cap_add:
            - NET_BIND_SERVICE
        restart: always
    
    frontend:
        image: frontend:builder
        container_name: frontend
        build:
            context: ./frontend
        volumes:
            - frontend-files:/www:cached
        networks:
            42network:
                aliases:
                    - frontend
        depends_on:
            - rest_api
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 256M
                reservations:
                    cpus: '0.25'
                    memory: 128M
        restart: always

    database:
        image: postgresql:database
        container_name: database
        build:
            context: ./infrastructure/postgres
        volumes:
            - database-data:/var/lib/postgresql/data
        networks:
            42network:
                aliases:
                    - database
                    - postgresql
        secrets:
            - database-credentials
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 15s
            timeout: 10s
            retries: 5
            start_period: 50s
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: always

    redis:
        image: redis:cache
        container_name: redis
        build:
            context: ./infrastructure/redis
        networks:
            42network:
                aliases:
                    - redis
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        depends_on:
            database:
                condition: service_healthy
        restart: always

    rest_api:
        image: restapi:server
        container_name: rest_api
        build:
            context: ./rest_api
        networks:
            42network:
              aliases:
                  - oauth
                  - api_gateway
        volumes:
            - shared-static_files:/app/media:rw
        secrets:
            - api-credentials
            - database-credentials
        depends_on:
            database:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 256M
        restart: always

    # prometheus:
    #     image: prometheus:monitoring
    #     container_name: prometheus
    #     build:
    #         context: ./monitoring/prometheus
    #     volumes:
    #         - prometheus-data:/prometheus
    #     networks:
    #         42network:
    #             aliases:
    #                 - prometheus
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: '0.25'
    #                 memory: 128M
    #             reservations:
    #                 cpus: '0.10'
    #                 memory: 64M
    #     restart: always
    #
    # node-exporter:
    #     image: node-exporter:monitoring
    #     container_name: node-exporter
    #     build:
    #         context: ./monitoring/node-exporter
    #     volumes:
    #         - /:/host:ro
    #     networks:
    #         42network:
    #             aliases:
    #                 - node-exporter
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: '0.10'
    #                 memory: 64M
    #             reservations:
    #                 cpus: '0.05'
    #                 memory: 32M
    #     restart: always
    #
    # grafana:
    #     image: grafana:monitoring
    #     container_name: grafana
    #     build:
    #         context: ./monitoring/grafana
    #     volumes:
    #         - grafana-data:/var/lib/grafana
    #     networks:
    #         42network:
    #             aliases:
    #                 - grafana
    #     depends_on:
    #         - prometheus
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: '0.25'
    #                 memory: 128M
    #             reservations:
    #                 cpus: '0.10'
    #                 memory: 64M
    #     restart: always


volumes:
    database-data:
        name: database-data
    frontend-files:
        name: frontend-files
    shared-static_files:
        name: shared-static_files
    # prometheus-data:
    #     name: prometheus-data
    # grafana-data:
    #     name: grafana-data


networks:
    42network:
        name: 42network
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1450


secrets:
    database-credentials:
        file: ../secrets/database-credentials.env
    api-credentials:
        file: ../secrets/api-credentials.env
