name: Deploy Prebuilt Container to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: MessaPongApp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/haguezoum/messa-pong:latest
          slot-name: production
          # Optional: If you want to use a specific resource group
          # resource-group: YourResourceGroupName
          # Optional: If you want to use a specific region
          # region: YourRegion

      - name: Post Deployment
        run: |
          echo "Deployment to Azure Web App completed successfully."
          echo "You can access your app at: https://<your-app-name>.azurewebsites.net"
          # Optionally, you can add more steps here, like sending notifications or running tests.
      - name: Notify Deployment Success
        run: |
          echo "Deployment to Azure Web App completed successfully."
          # You can add more notification steps here, like sending a message to Slack or email.
          # For example, using curl to send a message to a webhook:
          # curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment successful!"}' https://hooks.slack.com/services/your/webhook/url
          # Or using a GitHub Action to send a notification:
          # - name: Send Slack Notification